In [30]:
# 2. importamos librerias
import sys
import pandas as pd
import numpy as np

In [29]:
# 3. cargar datos de lectura
# En la evaluacion, los ficheros CSV se encuentran en /workspace
# para no complicarnos, utilizo esta porcion del codigo para
# no realizar cambios manuales antes de entregar
from pathlib import Path

ruta_datos = Path("/workspace")

if not ruta_datos.exists():
    ruta_datos = Path(".")

df_sales = pd.read_csv(ruta_datos / "sales.csv")
df_inventories = pd.read_csv(ruta_datos / "inventories.csv")
df_satisfaction = pd.read_csv(ruta_datos / "satisfaction.csv")

In [28]:
# Limpieza de datos 
df_sales = df_sales.dropna()
df_inventories = df_inventories.dropna()
df_satisfaction = df_satisfaction.dropna()

df_sales["Fecha_Venta"] = pd.to_datetime(df_sales["Fecha_Venta"])
df_inventories["Fecha_Actualización"] = pd.to_datetime(df_inventories["Fecha_Actualización"])
df_satisfaction["Fecha_Evaluación"] = pd.to_datetime(df_satisfaction["Fecha_Evaluación"])

In [ ]:
df_sales.head()

In [ ]:
df_inventories.head()

In [49]:
df_satisfaction.head()

   ID_Tienda  Satisfacción_Promedio Fecha_Evaluación
0          1                     85       2023-01-15
1          2                     90       2023-01-15
2          3                     70       2023-01-15
3          4                     65       2023-01-15
4          5                     55       2023-01-15

In [45]:
# 4.1 Ventas totales por producto y por tienda
df_sales.groupby(["ID_Tienda","Producto"])["Cantidad_Vendida"].sum().reset_index()

   ID_Tienda    Producto  Cantidad_Vendida
0          1  Producto A                20
1          1  Producto B                15
2          2  Producto A                30
3          2  Producto C                25
4          3  Producto A                10
5          3  Producto B                40
6          4  Producto A                25
7          4  Producto C                35
8          5  Producto B                20
9          5  Producto C                30

In [ ]:
# 4.2 Ingresos totales por tienda
df_sales["Total_Ventas"]= (df_sales["Cantidad_Vendida"]*df_sales["Precio_Unitario"])
df_sales.groupby("ID_Tienda")["Total_Ventas"].sum().reset_index()

   ID_Tienda  Total_Ventas
0          1          5000
1          2         10500
2          3          9000
3          4         13000
4          5         13000

In [46]:
#4.3 Resumen estadistico 
df_sales.describe()

       ID_Tienda  Cantidad_Vendida  Precio_Unitario  Total_Ventas
count  10.000000         10.000000        10.000000     10.000000
mean    3.000000         25.000000       190.000000   5050.000000
std     1.490712          9.128709        87.559504   3361.960407
min     1.000000         10.000000       100.000000   1000.000000
25%     2.000000         20.000000       100.000000   2625.000000
50%     3.000000         25.000000       200.000000   3500.000000
75%     4.000000         30.000000       275.000000   7875.000000
max     5.000000         40.000000       300.000000  10500.000000

In [ ]:
#4.4 Promedio de ventas por tienda y categoria

In [42]:
df_sales.groupby("Producto")["Total_Ventas"].sum().reset_index()

     Producto  Total_Ventas
0  Producto A          8500
1  Producto B         15000
2  Producto C         27000